sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dyf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dyf/react-test npm test

after_success:
  - docker build -t wakaka1123/multi-client ./client
  - docker build -t wakaka1123/multi-nginx ./nginx
  - docker build -t wakaka1123/multi-server ./server
  - docker build -t wakaka1123/multi-worker ./worker
  #login the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images to docker hub
  - docker push wakaka1123/multi-client
  - docker push wakaka1123/multi-nginx
  - docker push wakaka1123/multi-server
  - docker push wakaka1123/multi-worker
